# Generated by Django 2.0.5 on 2018-07-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
