# Generated by Django 2.0.5 on 2018-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0002_auto_20180704_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgboard',
            name='message',
            field=models.CharField(max_length=1024, verbose_name='留言信息'),
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='receiver',
            field=models.CharField(max_length=64, verbose_name='留言目标'),
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='sender',
            field=models.CharField(max_length=64, verbose_name='留言来源'),
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='留言时间'),
        ),
    ]
