# Generated by Django 2.0.5 on 2018-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0003_auto_20180711_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgboard',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
